USE [master]
GO

/****** Object:  Database [Quiz16]    Script Date: 4/9/2023 6:21:49 PM ******/
CREATE DATABASE [Quiz16]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SampleDatabaseForTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SampleDatabaseForTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SampleDatabaseForTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SampleDatabaseForTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Quiz16].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Quiz16] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Quiz16] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Quiz16] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Quiz16] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Quiz16] SET ARITHABORT OFF 
GO

ALTER DATABASE [Quiz16] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Quiz16] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Quiz16] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Quiz16] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Quiz16] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Quiz16] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Quiz16] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Quiz16] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Quiz16] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Quiz16] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Quiz16] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Quiz16] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Quiz16] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Quiz16] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Quiz16] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Quiz16] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Quiz16] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Quiz16] SET RECOVERY FULL 
GO

ALTER DATABASE [Quiz16] SET  MULTI_USER 
GO

ALTER DATABASE [Quiz16] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Quiz16] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Quiz16] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Quiz16] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Quiz16] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Quiz16] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Quiz16] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Quiz16] SET  READ_WRITE 
GO

